CSP refund calculation - Download from CST 

[Preparation]
1. Usage download from CST - Invoice Usage csv file
2. sub_list csv file

In [1]:
import pandas as pd
import dask.dataframe as dd

pd.options.display.float_format = '{:.7f}'.format

# Read Subscription List
#Filter by subID please Input "Y" after subName=
#no filter use please Input "N" after subName=
SubId = "N"

# Input your sublist file name in '' from read_csv('') including .csv file format
#subList=pd.read_csv('sub_llist.csv')['SubID'].values.tolist()

# Input your usage download file name after url= including .csv file format
url = 'Detail_BillingProfile_0419d453-bb34-424e-bf21-35cfcbd66842_202302_en.csv'

usage = dd.read_csv(url, usecols=['customerTenantId','customerName','subscriptionId', 'product','pricingModel','costInBillingCurrency','date',
                                  'reservationId','reservationName', 'benefitId']
                    ,low_memory=False
                   ,dtype={'reservationId': 'object',
       'reservationName': 'object','costInBillingCurrency': 'float64',
       'subscriptionId': 'object','benefitId': 'object'})

if(SubId=="Y"):
    filtered = usage.loc[usage["subscriptionId"].isin(subList)]
    pd_usage = filtered.compute()
else:
    pd_usage = usage.compute()

cal_usage = pd_usage.fillna('NaN')

print("Usage Filtering Done!!! Please proceed cell below!")

Usage Filtering Done!!! Please proceed cell below!

In [2]:
####Total Usage######################################################################################################
summary = pd.pivot_table(pd_usage, index=["customerName","customerTenantId","subscriptionId","product"], 
                         values=["costInBillingCurrency"], aggfunc="sum", margins=True, margins_name="Total")
result = pd.DataFrame(summary.to_records())
display(summary)

                                                                                                                                           costInBillingCurrency
customerName customerTenantId                     subscriptionId                       product
ADTCAPS      7618a958-e7c4-49d8-909a-012091dfc109 409b5443-b503-4b86-a46f-1a1085776d23 Application Gateway WAF v2 - KR Central                    801093.2629765
                                                                                       Azure Monitor - Emails                                          0.0000000
                                                                                       Backup - Azure VM - KR Central                              48466.5750000
                                                                                       Backup - Standard - KR Central                              22733.0870103
                                                                                       Bandwidth Inter-Region - Inter Continent - Inte...            241.9066420
...                                                                                                                                                          ...
코리안리재보험      bb25082a-4dc3-4ab0-9e8f-75e795ac014a 1f269331-3b1f-461a-ab5c-c907df0726c4 Virtual Network Private Link                                34038.7283189
                                                                                       Windows Server - 2 vCPU VM                                  73717.5926701
                                                                                       Windows Server - 4 vCPU VM                                 147428.5873204
                                                                                       Windows Server Burst - 2 vCPU VM                            12820.3072916
Total                                                                                                                                           63708975.6900419

[264 rows x 1 columns]

In [3]:
####Calculate Usage refund###########################################################################################
TotalAmount = 0
refund = 0
usageFlag = True

if(cal_usage.empty):
    print("#### No Usage ####")
else:
    usage = pd.pivot_table(pd_usage, index=["customerName","customerTenantId","subscriptionId"], values=["costInBillingCurrency"], aggfunc="sum", 
                          margins=True, margins_name="Total")

    TotalAmount = usage.tail(n=1)['costInBillingCurrency']
    refund = TotalAmount*0.1
    usage.reset_index(inplace=True)
    usage.loc[len(usage.index)] = ['','','Refund(Total*10%)',refund.values[0]]
    display(usage)

,customerName,customerTenantId,subscriptionId,costInBillingCurrency
0,ADTCAPS,7618a958-e7c4-49d8-909a-012091dfc109,409b5443-b503-4b86-a46f-1a1085776d23,7381655.7545863
1,ADTCAPS,7618a958-e7c4-49d8-909a-012091dfc109,4485bc5b-c6ab-4790-ad4b-cdaecda98849,2788678.5331807
2,ADTCAPS,7618a958-e7c4-49d8-909a-012091dfc109,756de852-8f84-4060-b620-5b5e788debaa,4298759.4837025
3,ADT캡스,a2137633-aeb7-42ce-8645-1d92885194f4,9d1c2855-4f6c-4489-91e4-f34696a87734,1506527.6174916
4,BETTERWAY SYSTEMS,27386dc8-72a6-4295-b214-a84e9c0ed5d8,9da91cda-3f45-4c6e-902c-b39e20f2de19,5913.0298535
5,Green Climate Fund,8b0acfec-73f2-47d9-a9ad-1b05fcec2e1e,093cdeca-d682-48e9-9b86-a6cbf67b0580,205644.7572517
6,Green Climate Fund,8b0acfec-73f2-47d9-a9ad-1b05fcec2e1e,943af7c3-183a-48db-af3c-16579741c29e,288464.5002839
7,Green Climate Fund,8b0acfec-73f2-47d9-a9ad-1b05fcec2e1e,f20c0fc3-9114-4add-98b2-156c2ded3c02,1.2633405
8,모두의연구소,99a3a274-d813-4071-af9e-b863e91f4a25,d3f789e1-6bfa-4c9e-8962-bd6729f8192a,109498.5576714
9,코리안리재보험,bb25082a-4dc3-4ab0-9e8f-75e795ac014a,1f269331-3b1f-461a-ab5c-c907df0726c4,47123832.1926797
10,Total,,,63708975.6900419
11,,,Refund(Total*10%),6370897.5690042

In [4]:
##Download
file_name = 'sarah_CSP.xlsx'
with pd.ExcelWriter(file_name) as writer:
    #total.to_excel(writer, sheet_name="Total Refund Amount", startrow=1, startcol=1)
    if(usageFlag):
        usage.to_excel(writer, sheet_name="Usage Refund Calc", startrow=1, startcol=1, index=False)
    #if(riFlag):
    #    purchase_ri.to_excel(writer, sheet_name="RI Refund Calc", startrow=1, startcol=1, index=False) 
    result.to_excel(writer, sheet_name="raw Usage Summary", startrow=0, startcol=0, index=False)
display("DONE!! file_name " + file_name)

'DONE!! file_name sarah_CSP.xlsx'